spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/repository
        #driver-class-name: org.postgresql.Driver
        #url: jdbc:postgresql://localhost:5433/repository
        username: root
        password: password

    jpa.properties.hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: update

    mvc.hiddenmethod.filter.enabled: true